version: '2'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
    #  - ./var/nginx:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt/
