version: '2'

services:
  flask:
    image: webapp-flask
    build:
      context: ../website/docker-flask-uwsgi-nginx
      dockerfile: Dockerfile-flask
    volumes:
      - "../website/docker-flask-uwsgi-nginx:/app"
  nginx:
    image: 'nginx:latest'
    ports:
      - 80:80
      - 443:443
      - 5000:80
    volumes:
      - ../website/wisemuffin:/app
    #  - ./var/nginx:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt/
    depends_on:
      - flask
